<a href="https://colab.research.google.com/github/sr606/Machine_Learning_CaseStudies/blob/main/BrandA_Loyalty_NonLoyalty_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Files/_cleaned_data_BrandA_Data_Loyalty_NonLoyalty.csv')

In [3]:
df.shape

(542419, 16)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542419 entries, 0 to 542418
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   customer_id                     269389 non-null  object
 1   currentTier                     269290 non-null  object
 2   customer_nationality            190437 non-null  object
 3   date_transacted                 542419 non-null  object
 4   storeId                         541242 non-null  object
 5   store_city                      542419 non-null  object
 6   transactionId                   541242 non-null  object
 7   itemid                          542419 non-null  object
 8   Brand                           542419 non-null  object
 9   itemName                        542419 non-null  object
 10  product_category                542419 non-null  object
 11  high_level_product_category     542419 non-null  object
 12  quantity                        542419 non-null  int64
 13  total_spend                     542419 non-null  float64
 14  signed_up_loyalty_program_date  269290 non-null  object
 15  signed_up_app_date              102155 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 66.2+ MB

In [26]:
df.head()

,customer_id,currentTier,customer_nationality,date_transacted,storeId,store_city,transactionId,itemid,Brand,itemName,product_category,high_level_product_category,quantity,total_spend,signed_up_loyalty_program_date,signed_up_app_date
0,CTFS302601-00002512-291660,Platinum,NaN,28-02-2022,A2001,Abu Dhabi,A2001-200102-97784,6793420,A,plain l/s blouse,BLOUSES,Blouses,1,160.95,18-09-2015,30-12-2018
1,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,242306,A,s/s t-shirt,M_KNITWEAR,Knitwear,1,39.00,03-11-2021,08-11-2021
2,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,247804,A,s/s t-shirts,M_KNITWEAR,Knitwear,1,25.00,03-11-2021,08-11-2021
3,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,378100,A,s/s casual shirt.fancy,SHIRTS,Shirts,1,59.00,03-11-2021,08-11-2021
4,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,437905,A,bermuda,M_TROUSERS,Bermuda,1,49.00,03-11-2021,08-11-2021

In [25]:
df.isnull().sum()

customer_id                       273030
currentTier                       273129
customer_nationality              351982
date_transacted                        0
storeId                             1177
store_city                             0
transactionId                       1177
itemid                                 0
Brand                                  0
itemName                               0
product_category                       0
high_level_product_category            0
quantity                               0
total_spend                            0
signed_up_loyalty_program_date    273129
signed_up_app_date                440264
dtype: int64

In [6]:
df.describe(include= 'all')

,customer_id,currentTier,customer_nationality,date_transacted,storeId,store_city,transactionId,itemid,Brand,itemName,product_category,high_level_product_category,quantity,total_spend,signed_up_loyalty_program_date,signed_up_app_date
count,269389,269290,190437,542419,541242,542419,541242,542419.0,542419,542419,542419,542419,542419.000000,542419.000000,269290,102155
unique,64989,3,261,759,20,8,227841,6318.0,1,169,18,22,NaN,NaN,2934,1010
top,CA202702-00014987-112614,Silver,United Arab Emirates,18-12-2020,A2011,Dubai,A2011-201101-37789,8551022.0,A,polo volume programs + basic slim fit,M_KNITWEAR,Knitwear,NaN,NaN,26-12-2013,20-12-2018
freq,187,230397,55378,3791,57876,186139,122,9067.0,542419,50225,245208,136132,NaN,NaN,1326,1379
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.940970,70.112451,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.402243,58.738807,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.000000,-912.760000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,42.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,65.710000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,94.280000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,2493.330000,NaN,NaN

In [20]:
df.describe()

            quantity    total_spend
count  542419.000000  542419.000000
mean        0.940970      70.112451
std         0.402243      58.738807
min        -3.000000    -912.760000
25%         1.000000      42.000000
50%         1.000000      65.710000
75%         1.000000      94.280000
max        22.000000    2493.330000

In [11]:
df_categorical_cols = [col for col in df.columns if df[col].nunique() < 50 and df[col].dtype == 'object']

df_categorical_cols

['currentTier',
 'storeId',
 'store_city',
 'Brand',
 'product_category',
 'high_level_product_category']

In [19]:
categorical_col_count = {col: df[col].nunique() for col in df_categorical_cols}
categorical_col_count

{'currentTier': 3,
 'storeId': 20,
 'store_city': 8,
 'Brand': 1,
 'product_category': 18,
 'high_level_product_category': 22}

In [18]:
df.columns

Index(['customer_id', 'currentTier', 'customer_nationality', 'date_transacted',
       'storeId', 'store_city', 'transactionId', 'itemid', 'Brand', 'itemName',
       'product_category', 'high_level_product_category', 'quantity',
       'total_spend', 'signed_up_loyalty_program_date', 'signed_up_app_date'],
      dtype='object')

#**🛠️ Basic Data Cleaning Implementation ✅**

Basic Data cleaning-


1.Removing null transaction ids.


2.Change datatype of itemid field from number to string.


3.Some values are missing in customer_nationality column, dealing with it.


4.Converting item id to string.

In [23]:
#Remove rows with null transaction IDs
df_cleaned = df.dropna(subset=['transactionId'])


#changing the datatype of itemidto string(categoriccal data)
df_cleaned['itemid'] = df_cleaned['itemid'].astype(str)

#filling missing values in customer_nationality column with unknown
df_cleaned['customer_nationality'].fillna('Unknwon', inplace = True)

#converting item_id into categorical data type()memory effeciency
df_cleaned['itemid'] =df_cleaned['itemid'].astype('category')

#**✅ Feature Engineering:**

**Client has given some information regarding the fields on that basis we will perform feature engineering**




1️⃣ Missing customer_id and signed_up_loyalty_program_date


🔍 Issue: Some transactions have customer_id but no loyalty sign-up date, while others have no customer_id at all(null values are non registered usrs given infromation from client )

✅ Solution: Creating a Registered field to classify customers as "Registered" or "Not Registered" for proper segmentation.



2️⃣ Negative total_spend values


🔍 Issue: Some transactions have negative total spend, indicating refunds, while others have zero spend but positive quantity, meaning freebies.


✅ Solution: Creating a Refund_Transaction field to classify transactions as "Sales", "Refund", or "Freebie" to track revenue correctly.

3️⃣ Negative quantity values


🔍 Issue: Some rows have negative quantities, suggesting refunded items rather than full transaction refunds.


✅ Solution: Creating an Item_Refunded field to mark refunded items separately, helping in product return analysis.

4️⃣ Missing values in currentTier


🔍 Issue: Some customers have no tier assigned, likely indicating they aren’t part of the loyalty program.


✅ Solution: Filling missing values with "No current tier" to prevent issues in filtering and grouping.

In [33]:
# Creating a field to check if a customer is registered

df_cleaned['Registered'] = df_cleaned.apply(lambda x: 'Registered' if pd.notnull(x['customer_id']) and pd.notnull(x['signed_up_loyalty_program_date']) else 'Guest Customer', axis = 1)
df_cleaned.head()

,customer_id,currentTier,customer_nationality,date_transacted,storeId,store_city,transactionId,itemid,Brand,itemName,product_category,high_level_product_category,quantity,total_spend,signed_up_loyalty_program_date,signed_up_app_date,Registered,Refund_Transactions
0,CTFS302601-00002512-291660,Platinum,Unknwon,28-02-2022,A2001,Abu Dhabi,A2001-200102-97784,6793420,A,plain l/s blouse,BLOUSES,Blouses,1,160.95,18-09-2015,30-12-2018,Registered,Sales
1,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,242306,A,s/s t-shirt,M_KNITWEAR,Knitwear,1,39.00,03-11-2021,08-11-2021,Registered,Sales
2,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,247804,A,s/s t-shirts,M_KNITWEAR,Knitwear,1,25.00,03-11-2021,08-11-2021,Registered,Sales
3,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,378100,A,s/s casual shirt.fancy,SHIRTS,Shirts,1,59.00,03-11-2021,08-11-2021,Registered,Sales
4,C202301-00003325-982140,Platinum,Russian Federation,28-02-2022,A2023,Doha,A2023-202301-56961,437905,A,bermuda,M_TROUSERS,Bermuda,1,49.00,03-11-2021,08-11-2021,Registered,Sales

In [29]:
df_cleaned['Registered'].value_counts()

Registered
Not Registered    271952
Registered        269290
Name: count, dtype: int64

In [31]:
# Creating a field to checks if the transaction was a refund or not
def classify_transactions(spend,quantity):
  if spend < 0:
    return 'Refund'
  elif spend == 0 and quantity > 0:
    return 'Freebie'
  else:
    return 'Sales'

df_cleaned['Refund_Transactions'] = df_cleaned.apply(lambda x: classify_transactions(x['total_spend'], x['quantity']), axis = 1)

In [32]:
df_cleaned['Refund_Transactions'].value_counts()

Refund_Transactions
Sales      515283
Refund      19213
Freebie      6746
Name: count, dtype: int64

In [34]:
#Creating a field to check if an item was refunded or not

df_cleaned['Item_Refunded'] = df_cleaned['quantity'].apply(lambda x: 'Refunded' if x < 0 else 'Not Refunded')

In [35]:
df_cleaned['Item_Refunded'].value_counts()

Item_Refunded
Not Refunded    521858
Refunded         19384
Name: count, dtype: int64

In [36]:
#Replacing nulls in currentTier with 'No current tier'

df_cleaned['currentTier'].fillna('No Current Tier', inplace= True)